### ISSUE TITLE
Does not work with Lua 5.2 and Lua 5.3

### ISSUE THREAD

**Issue by ignacio** [tylerneylon/lua_api_demo#1]
Hi. Just tried to install this with Lua 5.2 and 5.3 and it does not work. I presume that's because I have compiled 5.2 and 5.3 with compatibility flags disabled. (The code uses LUA_GLOBALSINDEX and that is not available).

**Comment by tylerneylon** [comment]
Hi Ignacio - I believe this is now fixed so that it builds correctly with LuaRocks on 5.1, 5.2, and 5.3, but I'd appreciate it if you could test it as well. I'm new to this stuff and may have missed something. Thanks!

**Comment by ignacio** [comment]
Done. Tested with 5.1, 5.2 and 5.3 on Windows (using Visual Studio 2015, won't build with older MS compilers) and the things I tried worked fine.

Are you interested in integrating Travis CI? I can submit a PR to do that, so you can build and run tests automatically.

Easy introduction:
https://blog.separateconcerns.com/2015-03-08-travis-lua.html

And a shameless plug:
http://www.slideshare.net/iburgueno/always-be-testing
https://www.youtube.com/watch?v=sLFwKeyH2Ug

**Comment by tylerneylon** [comment]
Thank you! I'll check out the links.
